stages:
  - build

build-docker-compose:
  stage: build
  image: docker/compose:latest
  variables:
    DOCKER_HOST: tcp://registry.gitlab.com
    DOCKER_TLS_CERTDIR: ""

  only:
    - dev
  services:
    - docker:dind
  before_script:
    - apk add ca-certificates
    - docker login -u Deployer -p ${ACCESS_TOKEN} registry.gitlab.com

  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up
