version: '1'
services:
  db:
    build: /database
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgresdb
      - PGDATA=/var/lib/postgresql/data/pgdatad
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  server:
    build: /server
    image: testdevops
    restart: always
    ports:
      - '8000:8000'
volumes:
  db:
    driver: local